### ISSUE TITLE
Este pacote está funcional?

### ISSUE THREAD

**Issue by eullercristian** [SintegraPHP/SC#1]
@jansenfelipe  Jeans, tudo bem? Este pacote está funcionando para os estados listados, ou está desatualizado?

**Comment by thiagocordeiro** [comment]
Olá @eullercristian, tudo bem? SC, MG estão funcionando, o estado de SP precisa ser atualizado e RS precisa ser feito (o branch está vazio)

**Comment by eullercristian** [comment]
Bacana @thiagocordeiro , vou dar uma olhada, atualmente uso uma api paga em um projeto na empresa, onde é pago um valor alto de mensalidade.

**Comment by thiagocordeiro** [comment]
@eullercristian, Legal, iniciamos este projeto baseado nas nossas necessidades em específico, mas acabamos não dando continuidade, além do mais, o @jansenfelipe tem outro projeto que consulta o CNPJ (https://github.com/jansenfelipe/cnpj-gratis) que é muito legal, vale a pena conferir, =D

**Comment by eullercristian** [comment]
@thiagocordeiro já dei um fork tanto nele quanto no de CPF. Vou fazer os testes. Obrigado pelo apoio =D
